import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:todo_app/utils/export_link.dart';

class LightTheme {
  static final ThemeData ligthTheme = ThemeData(
    useMaterial3: true,
    scaffoldBackgroundColor: AppColors.white,
    appBarTheme: AppBarTheme(
      backgroundColor: AppColors.white,
      systemOverlayStyle: SystemUiOverlayStyle(
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
        statusBarColor: AppColors.transparent,
      ),
    ),
    primaryColor: AppColors.black,
    disabledColor: AppColors.black.withOpacity(0.4),
    dividerColor: AppColors.black,
    canvasColor: const Color(0xFFFFFFFF),
    iconTheme: IconThemeData(
      color: AppColors.black,
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        textStyle: TextStyle(fontSize: 16.sp, fontFamily: "Lato", fontWeight: FontWeight.w500, color: AppColors.black),
      ),
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: AppColors.c9741CC,
      foregroundColor: AppColors.white,
    ),
    cardTheme: const CardTheme(color: Color(0xFFC4E3F7)),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF002B4A),
      surfaceTint: Color(0xFF6BB2F1),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF1B4E77),
      onPrimaryContainer: Color(0xFFD7E9FF),
      secondary: Color(0xFF616200),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFA1A241),
      onSecondaryContainer: Color(0xFF101000),
      tertiary: Color(0xFF366B00),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFF94FF36),
      onTertiaryContainer: Color(0xFF295300),
      error: Color(0xFF815600),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFF5A815),
      onErrorContainer: Color(0xFF3D2700),
      surface: Color(0xFF443939),
      onSurface: Color(0xFF1C1B1B),
      onSurfaceVariant: Color(0xFF42474E),
      outline: Color(0xFF72777F),
      outlineVariant: Color(0xFFC2C7CF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF313030),
      inversePrimary: Color(0xFF9ECBFA),
      primaryFixed: Color(0xFFCFE5FF),
      onPrimaryFixed: Color(0xFF001D34),
      primaryFixedDim: Color(0xFF9ECBFA),
      onPrimaryFixedVariant: Color(0xFF154A72),
      secondaryFixed: Color(0xFFE7E87E),
      onSecondaryFixed: Color(0xFF1C1D00),
      secondaryFixedDim: Color(0xFFCBCC65),
      onSecondaryFixedVariant: Color(0xFF494900),
      tertiaryFixed: Color(0xFF89FE0A),
      onTertiaryFixed: Color(0xFF0C2000),
      tertiaryFixedDim: Color(0xFF77DF00),
      onTertiaryFixedVariant: Color(0xFF275000),
      surfaceDim: Color(0xFFDDD9D9),
      surfaceBright: Color(0xFFDA8A8A),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF7F3F2),
      surfaceContainer: Color(0xFFF1EDEC),
      surfaceContainerHigh: Color(0xFFEBE7E7),
      surfaceContainerHighest: Color(0xFFE5E2E1),
    ),
    textTheme: TextTheme(
      displayLarge: TextStyle(
        fontSize: 57.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      displayMedium: TextStyle(
        fontSize: 45.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      displaySmall: TextStyle(
        fontSize: 36.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      headlineLarge: TextStyle(
        fontSize: 32.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      headlineMedium: TextStyle(
        fontSize: 28.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      headlineSmall: TextStyle(
        fontSize: 24.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      titleLarge: TextStyle(
        fontSize: 22.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      titleMedium: TextStyle(
        fontSize: 16.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      titleSmall: TextStyle(
        fontSize: 14.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      labelLarge: TextStyle(
        fontSize: 14.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      labelMedium: TextStyle(
        fontSize: 12.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      labelSmall: TextStyle(
        fontSize: 11.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      bodyLarge: TextStyle(
        fontSize: 16.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      bodyMedium: TextStyle(
        fontSize: 14.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
      bodySmall: TextStyle(
        fontSize: 12.sp,
        color: AppColors.black,
        fontWeight: FontWeight.w400,
        fontFamily: "Lato",
      ),
    ),
  );
}
